In [7]:
!pip install numpy


In [8]:
import numpy as np

## create array using numpy
## Create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # Single dimension with 5 elements



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## This become 2D array


array([[1, 2, 3, 4, 5]])

In [10]:
## 2D Arrays

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
##Attributes of arrays
arr= np.array([[1,2,3,4],[5,6,7,8]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Number of dimensions: 2
Size (number of elements): 8
Data Type: int64
Item size (in bytes): 8


In [15]:
## Numpy vectorised operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50]) ## size should be same of both the arrays

# Elements wise addition
print("Addition",arr1+arr2)

#Subsytaction
print("Substraction:",arr1-arr2)

Addition [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]


In [16]:
## Universal function
arr = np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [17]:
## Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [18]:
element = arr[0][3]
print(element)

4


In [21]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
print(arr[0][0])
print(arr[0:2,2:]) # row and column

1
[[3 4]
 [7 8]]


In [34]:
## Modify the elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
##Statistical Concepts -> Normalisation (mean=0 , SD=1)
# To have a mean of 0 and standard deviation
data=np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev = np.std(data)

normalised_data = (data-mean)/std_dev
print("Normalised Data : ",normalised_data)

Normalised Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [43]:
## Logical Operations

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])